Added functionality to add a user to the Firebase list
box86rowh/TwitchTV pull request #5
Opened 2017-03-24 21:39 UTC by dpberry552

The "Add New User" button will now pass the text from the new user input
box to the "addUser" method, which calls a service to add the new name
to the list of usernames stored in Firebase.

2017-03-24 23:26 UTC, box86rowh commented on src/app/twitch-manage-users/twitch-manage-users.component.html
> +        <button (click)="addNewUser(newUser)" type="button" class="btn btn-primary">Add New User</button>
you can just do - addNewUser() here

2017-03-24 23:27 UTC, box86rowh commented on src/app/twitch-manage-users/twitch-manage-users.component.ts
> +  addNewUser(un: string){
you can just do addNewUser() - no need to pass the username in, it is already in scope, you can just refer to this.userName within this function

2017-03-24 23:27 UTC, box86rowh requested changes
see comments for requested changes

2017-03-25 00:30 UTC, dpberry552 commented
Made the change...did you see it come through?

2017-03-25 00:31 UTC, box86rowh commented
yes! Merging...

2017-03-25 00:31 UTC, merged